brew install --cask alt-tab
brew install --cask graphviz
brew install --cask grep
brew install --cask iterm2
brew install --cask karabiner-elements
brew install --cask linearmouse
brew install --cask monitorcontrol
brew install --cask pinta
brew install --cask pinniped-cli 
brew install --cask rectangle